name: google_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: RobotoC
      fonts:
        - asset: fonts/RobotoCondensed-Light.ttf
    - family: KronaOne
      fonts:
        - asset: fonts/KronaOne-Regular.ttf